### ISSUE TITLE
Move lecture notebooks from https://github.com/jrjohansson/qutip-lectures

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip-notebooks#109]
There are some very interesting and valuable resources written by @jrjohansson which are linked on the QuTiP page:
https://github.com/jrjohansson/qutip-lectures

I recently used one of them and noticed small bugs and simple things that required updating. Having them in the  qutip-notebooks repository would make things much easier and if @jrjohansson and the rest of @qutip/qip-devs do not have any issues, I suggest we move these lecture notebooks here and check that they are updated properly.

@ajgpitch @nathanshammah What do you say?

**Comment by nathanshammah** [comment]
I agree and indeed I proposed this in #96. See @IvanIsCoding proposal there (it would be great to have also your input @IvanIsCoding is possible, on the testing side).

**Comment by quantshah** [comment]
Let's continue the discussion on that thread. Sorry to have missed that.
