### ISSUE TITLE
Broken links in Lecture 0

### ISSUE THREAD

**Issue by purva-thakre** [qutip/qutip-notebooks#113]
There are some broken links in Lecture 0 -  Introduction to QuTiP - The Quantum Toolbox in Python (found [here](http://qutip.org/tutorials.html)). Since I cannot find this on Github to make a pull request, I have created an issue. The new changes are itemized according to subsection. 

**Introduction** - For more information see the project web site at ~~http://qutip.googlecode.com~~ http://qutip.org/, and the documentation at ~~http://qutip.googlecode.com/svn/doc/2.1.0/html/index.html~~ http://qutip.org/documentation.html. 

**Installation** - To install QuTiP, download the latest release from ~~http://code.google.com/p/qutip/downloads/list~~  http://qutip.org/download.html  or get the latest code from

For more detailed installation instructions and a list of dependencies that must be installed on the system (basically python+cython+numpy+scipy+matplotlib), see ~~http://qutip.googlecode.com/svn/doc/2.1.0/html/installation.html~~ http://qutip.org/docs/latest/installation.html#building-your-conda-environment.

**Comment by nathanshammah** [comment]
Thanks. This is because the lecture notes are from another repository, Rob Johansson's. We've been discussing forking / copying them in qutip-notebooks to make the repo more manageable. See #96. You can try open a PR here directly https://github.com/jrjohansson/qutip-lectures.

**Comment by purva-thakre** [comment]
Thank you for pointing me to the correct repository.

**Comment by purva-thakre** [comment]
@nathanshammah Do you happen to know if someone is working on copying these lectures in qutip-notebooks ? 
I see the discussion in #96 and a proposed solution.

**Comment by deeksha-singh030** [comment]
@nathanshammah Few links are still not working in Lecture-0-Introduction to QuTip.

**Comment by hodgestar** [comment]
Closing this issue in favour of https://github.com/qutip/qutip-tutorials/issues/14 in the new qutip-tutorials repo.
