### ISSUE TITLE
Link to inexistent notebook

### ISSUE THREAD

**Issue by MrRobot2211** [qutip/qutip-notebooks#126]
Hi  I did not know if to create an issue here or in the documentation side. 

At the end of  [this]( http://qutip.org/docs/latest/guide/guide-tensor.html?highlight=product) documentationpage  there is a link to this  void [notebook](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/example-superop-contract.ipynbl). I searched for it here but could not find it.

**Comment by BoxiLi** [comment]
The link was wrong, it is supposed to link to https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/superop-contract.ipynb

**Comment by MrRobot2211** [comment]
Thnk you @BoxiLi  I'll change it in the docs then.
