### ISSUE TITLE
Relicense notebooks to BSD license

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip-notebooks#146]
As part of the GSoC QuTiP notebooks upgrade, I discovered that the qutip-notebooks are licensed under the LGPL. This was likely a mistake made ages ago (2013) and I would like to propose that we relicense the notebooks to the BSD license. Reasons and what's entailed follow:

## Why relicense?

- The LGPL license is a GPL license with an exception that allows software to link to a library at run-time without also having to be (L)GPLed. The qutip-notebooks repository doesn't contain a library.
- qutip and our other Python packages use the BSD licenses, which is not a copyleft license.
- As things stand, we don't have permission to use code from qutip-notebooks in qutip itself, and no one using qutip-notebooks could distribute copied or modified versions of code from qutip-notebooks without also licensing their work as LGPL.
- I don't think this situation makes much sense and I don't think it's what we or many of our users want. Currently our users would have to license their wrork as (L)GPL if they used a snippet of code from an example notebook.

## What's required to make the change?

- Since the LGPL doesn't grant us the freedom to distribute the notebook under a BSD license, we'll need to ask all contributors for permission to release their work under a BSD license.
- Luckily there are only ~15 contributors, and most of them are contactable.
- If we can't contact everyone, we can not re-license the specific notebooks affected (hopefully a small number).

## License change PR

- See #145 for the PR proposing the change to the BSD license.

## Re-licensing checklist

Below is a check list of the contributors we need to get permission to relicense from (in order of number of commits at the time of making the list):

- [x] [jrjohansson](https://github.com/jrjohansson)
- [x] [anubhavvardhan](https://github.com/anubhavvardhan)
- [x] [hodgestar](https://github.com/hodgestar)
- [x] [BoxiLi](https://github.com/BoxiLi)
- [x] [ajgpitch](https://github.com/ajgpitch)
- [x] [christian512](https://github.com/christian512)
- [x] [quantshah](https://github.com/quantshah)
- [x] [nathanshammah](https://github.com/nathanshammah)
- [x] [JonathanUlm](https://github.com/JonathanUlm)
- [x] [sbisw002](https://github.com/sbisw002)
- [x] [kafischer](https://github.com/kafischer)
- [x] [nonhermitian](https://github.com/nonhermitian)
- [x] [nwlambert](https://github.com/nwlambert)
- [x] [Ericgig](https://github.com/Ericgig)
- [x] [cgranade](https://github.com/cgranade)
- [x] [stared](https://github.com/stared)
- [x] [AGaliciaMartinez](https://github.com/AGaliciaMartinez)
- [x] [pmenczel](https://github.com/pmenczel)
- [x] [arnelg](https://github.com/arnelg)
- [x] [Vutshi](https://github.com/Vutshi)
- [x] [Amelie-og](https://github.com/Amelie-og)
- [x] [fminga](https://github.com/fminga)
- [x] [bencbartlett](https://github.com/bencbartlett)
- [x] [deeksha-singh030](https://github.com/deeksha-singh030)
- [x] [Leo-am](https://github.com/Leo-am)
- [x] [jakelishman](https://github.com/jakelishman)
- [x] [IvanIsCoding](https://github.com/IvanIsCoding)

In order to check someone off the list, they need to agree in writing to have their contributions released under the BSD license, preferably by write a comment on this issue stating "I agree to have my contributions to the qutip-notebooks released under the BSD license."

**Comment by hodgestar** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by jakelishman** [comment]
I agree to have my contributions to qutip-notebooks relicensed under BSD.

**Comment by Ericgig** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by christian512** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by quantshah** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by BoxiLi** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by ajgpitch** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by nwlambert** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by jrjohansson** [comment]
Good idea.

I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by pmenczel** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by bencbartlett** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by hodgestar** [comment]
@arnelg @Vutshi @fminga @deeksha-singh030 @IvanIsCoding @JonathanUlm @sbisw002 Apologies for directly pinging you. We'd like to re-license the QuTiP notebooks to BSD and it would be extremely helpful to have your permission to re-license your respective contributions.

You can do so by writing something like "I agree to have my contributions to the qutip-notebooks released under the BSD license." as a comment in this issue.

The issue description contains more details on why we'd like to make this change.

Thank your for reading and please let me know if you have any questions.

**Comment by arnelg** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license

**Comment by stared** [comment]
Sure, whatever works best for the project!
Personally, I am much more in favor of MIT/BSD licenses for their permissive nature.

So, hereby:
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by IvanIsCoding** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license

**Comment by Vutshi** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by sbisw002** [comment]
I agree to have my contributions to the qutip-notebooks released under the
BSD license.

Saumya Biswas

**Comment by deeksha-singh030** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license

**Comment by hodgestar** [comment]
@kafischer wrote to me by email and gave permission to relicense their contributions.

**Comment by Amelie-og** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license. :)

**Comment by fminga** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by JonathanUlm** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by cgranade** [comment]
I agree to have my contributions to the qutip-notebooks released under the BSD license.

**Comment by hodgestar** [comment]
@anubhavvardhan @Leo-am Apologies for directly pinging you. We'd like to re-license the QuTiP notebooks to BSD and it would be extremely helpful to have your permission to re-license your respective contributions.

You can do so by writing something like "I agree to have my contributions to the qutip-notebooks released under the BSD license." as a comment in this issue.

The issue description contains more details on why we'd like to make this change.

Thank your for reading and please let me know if you have any questions.

**Comment by anubhavvardhan** [comment]
I agree to have my contributions to qutip-notebooks relicensed under BSD.

**Comment by hodgestar** [comment]
Thank you everyone for making this an amazingly quick and painless re-licensing process! Enjoy the BSD licensed notebooks. :D
