### ISSUE TITLE
Moving to jupyter?

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip-notebooks#26]
@cgranade @nonhermitian @jrjohansson Should I avoiding converting existing notebooks to version 4 (jupyter) format? I see that they run fine on the nb server. However, someone I was working with found that they could not open my new notebook because they were still on ipython nb v3. Should we expect users to upgrade to v4?

**Comment by cgranade** [comment]
I think it makes sense to hold back updating as long as is reasonable, esp. given Windows install hassles.

**Comment by ajgpitch** [comment]
Would I be correct in thinking the best way to achieve this is to set up an anaconda env with an old version of ipython notebook. I have not seen any way to save a backwards compatible notebook from within jupyter

**Comment by ajgpitch** [comment]
Ok, well after spending some time setting up a new env for editing notebooks, I found that you need a pretty old version of Ipython before is saves in v3 nb format. The IPython people seem pretty keen for people to the later version. I have decided therefore that I will continue editing in jupyter, but then use
$ ipython nbconvert --to notebook --nbformat 3 <notebook>
to create a nb v3 format copy.
This way the website will point to a the v4 nb, but there will be a copy that anyone still using old format can download from here. I hope that is satisfactory.

**Comment by ajgpitch** [comment]
The PR #31 adds instructions on how to downgrade v4 notebooks.
I have moved the v3 copies to a subdir, as I think it was a bit messy. However I realise that this will cause those with linked images to fail. We could of course copy all the images, however this is messy again.
Do we think that the instructions on downgrading are enough? I would prefer not to have the nbv3 copies there at all.

**Comment by nathanshammah** [comment]
This issue seems taken care of by #68.
