### ISSUE TITLE
mybinder - updating

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip-notebooks#28]
@nonhermitian The new binder thing is awesome! Great find
How is it updated? As in when we get a fix for the version table issue done, how do we update the mybinder configuration.

I guess we should put a badge on this readme as well, and on the QuTiP website. Everyone agree?

**Comment by nonhermitian** [comment]
Not exactly sure.  I think we just need to rerun the binder 'make' setup.  Also, there is already a badge on the readme.

**Comment by ajgpitch** [comment]
I will have a go at the binder 'make' setup then.

Yes, I was making other changes to the readme, so I added the badge then.
I will be making a link to the Andrew Dawes lectures from qutip.org soon too, so I will add the binder badge then as well.
