### ISSUE TITLE
negative expectation values in tutorial

### ISSUE THREAD

**Issue by marekyggdrasil** [qutip/qutip-notebooks#50]
Obviously I'm new to QuTip, while browsing I noticed y-axis in those graphs is marked as `expectation value` however expectation value is representing a measurement it cannot be negative.

https://github.com/qutip/qutip-notebooks/blob/0adaa9a51b98aa6c513a978c05e810a20fb7530b/examples/qubit-dynamics.ipynb

**Comment by nathanshammah** [comment]
Probabilities cannot be negative.  Measurements of observables can be negative. For example a spin projected on a given direction can point up (+1) or down (-1) and oscillate, as shown in these plots.
