### ISSUE TITLE
ENH: Add ReviewNB bot to simplify notebook review of PRs

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-notebooks#95]
[Review NB](https://www.reviewnb.com/) allows to review more easily changes in Jupyter Notebooks. It seems perfect for this repository.

**Comment by hodgestar** [comment]
A different approach to reviewability has been taken in https://github.com/qutip/qutip-tutorials, namely to store the notebooks directly as markdown notebooks.

I'm not sure this gives us everything Review NB does (specifically it would be nice to be able to see how the output has changed if the notebook is also present in the target branch for the PR) but I'm going to close this for now.
