### ISSUE TITLE
Number QuTiP tutorials

### ISSUE THREAD

**Issue by LarsSchaaf** [qutip/qutip-notebooks#98]
Momentarily it is difficult to follow the examples coherently because the order is alphabetical. Would it be possible to add numbers to all the examples?

**Comment by nathanshammah** [comment]
Good point. I thought about this. By the way, the tutorials are more ordered on http://qutip.org/tutorials.html

**Comment by TejasAvinashShetty** [comment]
I beg to differ. Alphabetic sorting helps group similar examples together.

**Comment by TejasAvinashShetty** [comment]
![image](https://user-images.githubusercontent.com/27445854/75608597-f2495b00-5b26-11ea-8b34-e4ab3f53cde6.png)
